package dev.kortex.core.pattern

import dev.kortex.core.graph.AgentContext
import dev.kortex.core.graph.Node
import dev.kortex.core.graph.complete
import dev.kortex.core.llm.LlmRequest
import dev.kortex.core.llm.Models
import dev.kortex.core.log.d
import dev.kortex.core.log.w
import dev.kortex.core.state.AgentState
import dev.kortex.core.state.Message
import dev.kortex.core.state.Plan
import dev.kortex.core.state.PlanStep
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject

/**
 * Pattern 6 (Planning), T4.2. Runs ONE pending [PlanStep] per graph pass — the graph's
 * self-loop drives iteration, keeping each pass small and budget-checked by the runner
 * between passes.
 *
 * Each step gets a **scoped, ephemeral message list** (the run's SYSTEM message + one
 * USER message with the overall goal, completed-step results, and the current step's
 * instruction) instead of the ever-growing transcript — that focused context is the
 * whole point of planning. The inner Think→Act→Observe loop mirrors [ReActNode]
 * (governor, approval flow, budget updates) but is capped at [maxIterationsPerStep].
 *
 * The scoped ASSISTANT/TOOL messages are NOT appended to `state.messages` (context
 * bloat); only the step's outcome survives, truncated to ~[MAX_RESULT_CHARS] chars,
 * inside [PlanStep.result]. A FAILED step does not abort the plan — later steps and
 * the synthesizer see the failure and work around it.
 */
class ExecuteStepNode(
    private val model: String = Models.REASONING,
    private val maxIterationsPerStep: Int = 4,
) : Node {
    override suspend fun run(ctx: AgentContext, state: AgentState): AgentState {
        val plan = state.plan ?: return state
        val index = plan.nextPending ?: return state
        val step = plan.steps[index]
        ctx.onProgress.report("Step ${index + 1}/${plan.steps.size}: ${step.description}")
        ctx.logger.d(TAG, "step ${index + 1}/${plan.steps.size}: ${step.description}")

        val goal = state.goal?.description
            ?: state.messages.lastOrNull { it.role == Message.Role.USER }?.content.orEmpty()

        // Scoped, ephemeral context — never merged back into state.messages.
        var scoped = listOfNotNull(
            state.messages.firstOrNull { it.role == Message.Role.SYSTEM },
            Message(Message.Role.USER, stepPrompt(goal, plan, index)),
        )
        var s = state
        var answer = ""
        var failure: String? = null

        run loop@{
            repeat(maxIterationsPerStep) {
                val resp = ctx.complete(LlmRequest(model = model, messages = scoped, tools = ctx.tools.all()))
                s = s.copy(
                    budget = s.budget.copy(
                        tokensUsed = s.budget.tokensUsed + resp.inputTokens + resp.outputTokens,
                    ),
                )
                scoped = scoped + resp.message

                if (!resp.wantsTools) {
                    answer = resp.message.content
                    return@loop
                }

                val turnAttachments = mutableListOf<dev.kortex.core.state.Attachment>()
                for (call in resp.message.toolCalls) {
                    ctx.onProgress.report("Tool usage: ${call.name}")
                    val tool = ctx.tools.get(call.name)
                    val result = if (tool == null) {
                        ctx.logger.w(TAG, "unknown tool requested: '${call.name}'")
                        dev.kortex.core.tool.ToolResult(false, "Unknown tool '${call.name}'")
                    } else {
                        val args = runCatching { Json.parseToJsonElement(call.argumentsJson) as JsonObject }
                            .getOrDefault(JsonObject(emptyMap()))
                        ctx.governor.run(tool, args, s.budget, ctx.approver, ctx.logger)
                    }
                    s = s.copy(budget = s.budget.copy(toolCallsMade = s.budget.toolCallsMade + 1))
                    scoped = scoped + Message(Message.Role.TOOL, result.content, toolCallId = call.id)
                    turnAttachments.addAll(result.attachments)
                }

                if (turnAttachments.isNotEmpty()) {
                    scoped = scoped + Message(
                        Message.Role.USER,
                        "Attachments generated by the requested tools:",
                        attachments = turnAttachments,
                    )
                }

                if (s.budget.exhausted) {
                    failure = "budget exhausted before the step finished"
                    return@loop
                }
            }
        }

        if (answer.isBlank() && failure == null) {
            failure = "no answer within $maxIterationsPerStep iterations"
        }
        val status = if (failure == null) PlanStep.Status.DONE else PlanStep.Status.FAILED
        val outcome = failure ?: truncateAtWord(answer)
        val updated = plan.steps.toMutableList().also {
            it[index] = step.copy(status = status, result = outcome)
        }
        return s.copy(plan = Plan(updated))
            .trace("execute", "step", "${index + 1}:${status.name.lowercase()}")
    }

    /** The one focused USER message a step sees: goal, prior results, current instruction. */
    private fun stepPrompt(goal: String, plan: Plan, index: Int): String {
        val prior = plan.steps.take(index).mapIndexed { i, s ->
            "Step ${i + 1} — ${s.status.name.lowercase()}: ${s.result.ifBlank { "(no result)" }}"
        }
        return listOfNotNull(
            "Overall goal: $goal",
            prior.takeIf { it.isNotEmpty() }?.joinToString("\n", prefix = "Results so far:\n"),
            "Your task now — step ${index + 1} of ${plan.steps.size}: ${plan.steps[index].description}",
            "Complete ONLY this step, using tools as needed, then reply with the step's outcome as plain text.",
        ).joinToString("\n\n")
    }

    companion object {
        private const val TAG = "ExecuteStepNode"

        /** Step results feed later steps and synthesis — keep them summary-sized. */
        internal const val MAX_RESULT_CHARS = 800

        internal fun truncateAtWord(text: String, max: Int = MAX_RESULT_CHARS): String {
            if (text.length <= max) return text
            val cut = text.take(max)
            return cut.substringBeforeLast(' ', cut).trimEnd() + "…"
        }
    }
}
